[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
authors = [
  { name="Christopher McAdams", email="mca.christopher@gmail.com" }
]

name = "gnome-night-shift"
description = "Get Times of sunrise sunset for provided location"
dependencies = ["requests>=2.28.0","pycairo","PyGObject" ]
readme = "README.md"
requires-python = ">=3.0"
version = "0.3.0"

[project.urls]
Homepage = "https://github.com/christophermca/night-shift"

[project.scripts]
night-shift = "gnome_night_shift:main"
night-shift--initialize = "gnome_night_shift:Datastore"
night-shift-services = "gnome_night_shift.services:setup"
night-shift-remove-services = "gnome_night_shift.services:destroy"
night-shift--check-me = "gnome_night_shift.services:check_me"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]

dev = [
  "black", "locust"
]

[tool.setuptools.package-data]
 "*" =  ["schemas/*.xml", "services/systemd/user/*.timer", "services/systemd/user/*.service"]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: Linux",
]
